[0m13:53:05.495419 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f738c9c1280>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f738c9eda60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f738cb7a900>]}


============================== 13:53:05.498768 | 5415a392-43f4-4be6-9ebb-5d3b3c0e22dd ==============================
[0m13:53:05.498768 [info ] [MainThread]: Running with dbt=1.9.2
[0m13:53:05.499205 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '/home/juan_hun/.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt init', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m13:53:05.505939 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'PosixPath'.. Dictionary: {'dir': PosixPath('/home/juan_hun/.dbt')}
[0m13:53:05.506362 [info ] [MainThread]: Creating dbt configuration folder at 
[0m13:53:21.024459 [debug] [MainThread]: Starter project path: /home/juan_hun/default/lib/python3.12/site-packages/dbt/include/starter_project
[0m13:53:21.031138 [info ] [MainThread]: 
Your new dbt project "custom_postgres" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m13:53:21.031602 [info ] [MainThread]: Setting up your profile.
[0m18:28:39.242634 [error] [MainThread]: Encountered an error:

[0m18:28:39.247773 [error] [MainThread]: Traceback (most recent call last):
  File "/home/juan_hun/default/lib/python3.12/site-packages/dbt/cli/requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/juan_hun/default/lib/python3.12/site-packages/dbt/cli/requires.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/juan_hun/default/lib/python3.12/site-packages/dbt/cli/main.py", line 477, in init
    results = task.run()
              ^^^^^^^^^^
  File "/home/juan_hun/default/lib/python3.12/site-packages/dbt/task/init.py", line 346, in run
    self.setup_profile(profile_name)
  File "/home/juan_hun/default/lib/python3.12/site-packages/dbt/task/init.py", line 262, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "/home/juan_hun/default/lib/python3.12/site-packages/dbt/task/init.py", line 179, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "/home/juan_hun/default/lib/python3.12/site-packages/dbt/task/init.py", line 163, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/juan_hun/default/lib/python3.12/site-packages/dbt/task/init.py", line 129, in generate_target_from_input
    target[key] = click.prompt(
                  ^^^^^^^^^^^^^
  File "/home/juan_hun/default/lib/python3.12/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "/home/juan_hun/default/lib/python3.12/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m18:28:39.250248 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 4154.1245, "process_in_blocks": "15592", "process_kernel_time": 0.203531, "process_mem_max_rss": "92896", "process_out_blocks": "80", "process_user_time": 0.930427}
[0m18:28:39.250738 [debug] [MainThread]: Command `dbt init` failed at 18:28:39.250590 after 4154.13 seconds
[0m18:28:39.251431 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f738c9eda60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f738c6226f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f738cc52300>]}
[0m18:28:39.252011 [debug] [MainThread]: Flushing usage events
[0m18:28:39.506902 [debug] [MainThread]: An error was encountered while trying to flush usage events
